<?php
// ローカル専用の Stripe 鍵設定（.gitignore 対象、コミットされません）。
// Stripe ダッシュボードで認証が完了したら、下の空欄に実際の鍵を入力してください。
return [
    'secret_key' => '',      // sk_test_... または sk_live_...
    'publishable_key' => '', // pk_test_... または pk_live_...
    'webhook_secret' => '',  // whsec_...
];
